<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5H50MM9" failures="3" tests="6" name="Testrunner.Testngtestrunner" time="649.893" errors="0" timestamp="2023-12-07T13:19:19 IST" skipped="0">
  <testcase classname="Testrunner.Testngtestrunner" name="runScenario" time="108.085"/>
  <testcase classname="Testrunner.Testngtestrunner" name="runScenario" time="108.254">
    <failure message="expected [No data] but found [Cucumber]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [No data] but found [Cucumber]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Stepdefintion.OfferpageStepdefintion.validate_productname_in_offer_page_matches_with_landing_page(OfferpageStepdefintion.java:59)
at ✽.Validate productname in offer page matches with landing page(file:///C:/Users/DELL/Gitstuff/src/test/java/featurefile/searchproduct.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Testrunner.Testngtestrunner" name="runScenario" time="108.155">
    <failure message="expected [No data] but found [Beetroot]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [No data] but found [Beetroot]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Stepdefintion.OfferpageStepdefintion.validate_productname_in_offer_page_matches_with_landing_page(OfferpageStepdefintion.java:59)
at ✽.Validate productname in offer page matches with landing page(file:///C:/Users/DELL/Gitstuff/src/test/java/featurefile/searchproduct.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Testrunner.Testngtestrunner" name="runScenario" time="108.701">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Stepdefintion.CheckoutpageStepdefintion.user_proceed_to_checkout_and_validate_the_item_in_checkout_page(CheckoutpageStepdefintion.java:24)
at ✽.user proceed to checkout and validate the cuc item in checkout page(file:///C:/Users/DELL/Gitstuff/src/test/java/featurefile/checkout.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Testrunner.Testngtestrunner" name="runScenario" time="108.224"/>
  <testcase classname="Testrunner.Testngtestrunner" name="runScenario" time="108.474"/>
</testsuite> <!-- Testrunner.Testngtestrunner -->
